-- MySQL Script generated by MySQL Workbench
-- Fri Jul 25 22:39:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LittleLemonDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LittleLemonDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LittleLemonDB` DEFAULT CHARACTER SET utf8 ;
USE `LittleLemonDB` ;

-- -----------------------------------------------------
-- Table `LittleLemonDB`.`CustomerDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`CustomerDetails` (
  `CustomerId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(150) NULL,
  PRIMARY KEY (`CustomerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`StaffRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`StaffRoles` (
  `RoleId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RoleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`StaffInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`StaffInfo` (
  `StaffId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Full Name` VARCHAR(150) NOT NULL,
  `Salary` DECIMAL NOT NULL,
  `RoleId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`StaffId`),
  CONSTRAINT `StaffRole_FK`
    FOREIGN KEY (`RoleId`)
    REFERENCES `LittleLemonDB`.`StaffRoles` (`RoleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `StaffRole_FK_idx` ON `LittleLemonDB`.`StaffInfo` (`RoleId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Bookings` (
  `BookingId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `BookingDate` DATE NOT NULL,
  `TableNumber` INT NOT NULL,
  `CustomerId` INT UNSIGNED NOT NULL,
  `StaffId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`BookingId`),
  CONSTRAINT `CustomerId`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `LittleLemonDB`.`CustomerDetails` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `StaffId`
    FOREIGN KEY (`StaffId`)
    REFERENCES `LittleLemonDB`.`StaffInfo` (`StaffId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `CustomerId_idx` ON `LittleLemonDB`.`Bookings` (`CustomerId` ASC) VISIBLE;

CREATE INDEX `StaffId_idx` ON `LittleLemonDB`.`Bookings` (`StaffId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`MenuItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`MenuItems` (
  `MenuItemsId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CourseName` VARCHAR(45) NOT NULL,
  `StarterName` VARCHAR(45) NOT NULL,
  `DessertName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MenuItemsId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Menu` (
  `MenuId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MenuName` VARCHAR(45) NOT NULL,
  `Cuisine` VARCHAR(45) NOT NULL,
  `MenuItemsId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`MenuId`),
  CONSTRAINT `MenuItemId`
    FOREIGN KEY (`MenuItemsId`)
    REFERENCES `LittleLemonDB`.`MenuItems` (`MenuItemsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `MenuItemId_idx` ON `LittleLemonDB`.`Menu` (`MenuItemsId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Orders` (
  `OrderId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `OrderDate` DATE NOT NULL,
  `Quantity` INT NOT NULL,
  `TotalCost` DECIMAL NOT NULL,
  `CustomerId` INT UNSIGNED NOT NULL,
  `MenuId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`OrderId`),
  CONSTRAINT `CustomerOrderId_FK`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `LittleLemonDB`.`CustomerDetails` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MenuOrder_FK`
    FOREIGN KEY (`MenuId`)
    REFERENCES `LittleLemonDB`.`Menu` (`MenuId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `CustomerOrderId_FK_idx` ON `LittleLemonDB`.`Orders` (`CustomerId` ASC) VISIBLE;

CREATE INDEX `MenuOrder_FK_idx` ON `LittleLemonDB`.`Orders` (`MenuId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`OrderDeliveryStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`OrderDeliveryStatus` (
  `StatusId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DeliveryDate` DATE NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `OderId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`StatusId`),
  CONSTRAINT `OrderDeliveryId`
    FOREIGN KEY (`OderId`)
    REFERENCES `LittleLemonDB`.`Orders` (`OrderId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `OrderDeliveryId_idx` ON `LittleLemonDB`.`OrderDeliveryStatus` (`OderId` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
